### PR TITLE
feat: Adds inline comments to utils.py

### PR DESCRIPTION
**Pull request by darigovresearch**
Would resolve Issue #71 if merged

## Description
Adds inline comments to utils.py

## Affected Dependencies
None

## How has this been tested?
- Viewed via the browser

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

### CODE REVIEW

**Review by ramesht007 — CHANGES_REQUESTED** [review]
Hi, @darigovresearch 
Thanks for the PR. 🙂
Can you please change the formating to [Sphinx documentation fromat](https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html).
For reference you can go through [this](https://github.com/OpenMined/Threepio/pull/116).

**Comment by darigovresearch** [comment]
Thanks @ramesht007 for the guidance.

An additional commit has been made, is it now suitable enough to merge?

**Review by ramesht007 — APPROVED** [review]
LGTM!

**Review by ramesht007 — APPROVED** [review]

**Review by Nolski — APPROVED** [review]

**Pull request merged**
